CREATE TABLE `MESSAGE`(
	ID				INT 	PRIMARY KEY AUTO_INCREMENT,
	MESSAGEID 		VARCHAR(255) 	NOT NULL,
	SENDID			VARCHAR(255) 	NOT NULL,
	RECID			VARCHAR(255)		NOT NULL,
	STATES			SMALLINT		NOT NULL
);

CREATE TABLE `MESSAGECONTENT`(
	MESSAGEID		VARCHAR(255) 	PRIMARY KEY ,
	CONTENT 		BLOB	NOT NULL,
	PDATE			VARCHAR(255)	NOT NULL
);

CREATE TABLE `MEMBERIMAGE`(
	ID				INT 			PRIMARY KEY AUTO_INCREMENT,
	MEMUUID 		VARCHAR(64) 	NOT NULL,
	IMAGEURL		VARCHAR(200) 	NOT NULL,
	MAINIMAGE		INT				DEFULT 0 ,
);

CREATE TABLE `MEMBER` (
  `MEMUUID` VARCHAR(255) NOT NULL,
  `MEMSEX` INT DEFAULT NULL,
  `MEMMAIL` VARCHAR(255) DEFAULT NULL,
  `MEMPWD` VARCHAR(255) DEFAULT NULL,
  `MEMDEP` VARCHAR(255) DEFAULT NULL,
  `MEMNICKNAME` VARCHAR(255) DEFAULT NULL,
  `MEMADDRESS` VARCHAR(255) DEFAULT NULL,
  `MEMAREA`		varchar(255) DEFAULT NULL,
  `MEMAGE` INT DEFAULT NULL,
  `MEMALCOHOL` INT DEFAULT NULL,
  `MEMASSETS` INT DEFAULT NULL,
  `MEMBIRTHDAY` VARCHAR(255) DEFAULT NULL,
  `MEMEDU` INT DEFAULT NULL,
  `MEMHEIGHT` INT DEFAULT NULL,
  `MEMINCOME` INT DEFAULT NULL,
  `MEMISVIP` INT DEFAULT NULL,
  `MEMLGD` INT DEFAULT NULL,
  `MEMMARRY` INT DEFAULT NULL,
  `MEMNAME` VARCHAR(255) DEFAULT NULL,
  `MEMPHONE` VARCHAR(255) DEFAULT NULL,
  `PHONESTATES` SMALLINT  DEFAULT 0,
  `MEMRDATE` VARCHAR(255) DEFAULT NULL,
  `MEMSMOKE` INT DEFAULT NULL,
  `MEMSTA` INT DEFAULT NULL,
  `MEMWEIGHT` INT DEFAULT NULL,
  `MEMPICURL` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`MEMUUID`)
) ;

ALTER table `MEMBER` add `PHONESTATES` SMALLINT  DEFAULT 0;
SELECT * FROM `MEMBERIMAGE` M  ;
SELECT * FROM `MEMBER` M2 ;

SELECT M.*,MC.CONTENT,MC.PDATE FROM `MESSAGE` M
JOIN MESSAGECONTENT MC ON M.MESSAGEID =MC.MESSAGEID; 

SELECT M.MEMUUID,M.MEMNAME,M.MEMNICKNAME,M.MEMAREA,M.memAddress  ,M.MEMLGD FROM MEMBER M ;
SELECT * FROM `MEMBER` ;
SELECT * FROM MESSAGECONTENT m ;
SELECT * FROM `MESSAGECONTENT` WHERE MESSAGEID ='EBAF4DE9-5167-4856-9753-568C00534BB3';

